### ISSUE TITLE
网络隔离

### ISSUE THREAD

**Issue by UCloudDocs** [UCloudDoc-Team/uk8s#24]
# 网络隔离

查看产品文档请点击下方链接

[https://docs.ucloud.cn/uk8s/network/networkpolicy](https://docs.ucloud.cn/uk8s/network/networkpolicy)

**Comment by zczm2** [comment]
版本已经出现差异，执行
kubectl apply -f https://gitee.com/uk8s/uk8s/raw/master/yaml/policy_calico-policy-only.yaml
报错
unable to recognize "https://gitee.com/uk8s/uk8s/raw/master/yaml/policy_calico-policy-only.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

**Comment by jaya-sun** [comment]
您好，关于上文提到的piextensions.k8s.io/v1beta1 差异版本已经被替换掉
