### ISSUE TITLE
ULB 参数说明

### ISSUE THREAD

**Issue by UCloudDocs** [UCloudDoc-Team/uk8s#72]
# ULB 参数说明

查看产品文档请点击下方链接

[https://docs.ucloud.cn/uk8s/service/annotations](https://docs.ucloud.cn/uk8s/service/annotations)

**Comment by yinheli** [comment]
`service.beta.kubernetes.io/ucloud-load-balancer-vserver-monitor-path` 如果是自定义，不要用 `/` 打头

**Comment by jaya-sun** [comment]
已收到您的反馈，文档已修改
