### ISSUE TITLE
no configMap in cni-vpc-ipamd.yml

### ISSUE THREAD

**Issue by CUGGJY** [UCloudDoc-Team/uk8s#8]
There is **no configMap in cni-vpc-ipamd.yml**, so Deployment cannot start. That's my problem? Or the files are actually missing?

**Comment by recall704** [comment]
do you mean `uk8sconfig`

you can find it here

![图片](https://user-images.githubusercontent.com/7451408/155317834-4f0b133a-2a0b-449e-ae06-ea0ae08817e9.png)
